import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Roboto } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../src/theme';
import Navbar from '../src/menu.tsx';
import Box from '@mui/material/Box';
import  TopBar from "../src/top_bar.tsx"
import Footer from '../src/footer.tsx';

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

const barlow = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-barlow',
});
export const metadata: Metadata = {
  title: "Nury Energia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt"  className={barlow.variable}>
      <body>
          <ThemeProvider theme={theme}>
            <AppRouterCacheProvider>
              <TopBar />
              <Box sx={{ mt: '69px',mb: '40px' }}>
                <Navbar />
                {children}
              </Box>
              <Footer sx={{ mt: 8 }}/>
            </AppRouterCacheProvider>
          </ThemeProvider>
      </body>
    </html>
  );
}
